### ISSUE TITLE
Telas de login e cadastro não estão acessíveis a um usuário

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#120]
## Descrição do problema

Ao entrar no sistema não é possível acessar as telas de Login e Cadastro da aplicação por nenhuma opção da aplicação.

## Passos para reprodução

Passos para reproduzir o comportamento.

1. Abrir a aplicação
2. Tentar fazer login ou cadastro sem modificar a URL

### Comportamento atual

Não é possível encontrar uma opção correspondente

### Comportamento esperado

Encontrar uma opção de login e uma de cadastro

## Possível Solução

Criar um botão de login e linkar a página de Login a esse botão

**Comment by icaropires** [comment]
Aparentemente também está ocorrendo outro erro relacionado com as rotas, porque com a build de produção não é possível nem acessar os paths manualmente.

Checar referência:
https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually

**Comment by tmcstiago** [comment]
Para resolver este problema, a página de Login foi definida como página inicial do sistema e foi a funcionalidade de incluir novo usuário foi incluída em uma das opções do menu lateral, além de ter o redirecionamento através do botão "Cadastrar" da página de Login.
