### ISSUE TITLE
Modificar códigos das respostas do GraphQL

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#134]
## Descrição

Arrumar códigos das respostas HTTP vindas do GraphQL

## Tarefas

- [ ] Checar como configurar os códigos HTTP de resposta;
- [ ] Realizar configuração nas funções de query;
- [ ] Realizar testes unitários.

## Informação adicional

Todas as requisições estão sendo respondidas com código 200

**Comment by GabrielTiveron** [comment]
Dei uma pesquisada e parece que as respostas do graphql n correspondem ao response http mesmo, https://github.com/graphql-python/graphene/issues/142
É para tentar fazer essa mudança mesmo assim?
