### ISSUE TITLE
Conteúdo do token não está sendo checado

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#147]
## Descrição do problema

O conteúdo do token de sessão não está sendo checado, então qualquer um pode ser considerado logado na aplicação.

## Passos para reprodução

1. Entre no modo de desenvolvedor do navegador
2. Crie um cookie manualmente com a chave 'Token' e qualquer valor

### Comportamento atual

Usuário considerado logado

### Comportamento esperado

O token deveria ser considerado inválido

## Possível Solução

**Comment by GabrielTiveron** [comment]
Existe alguma duração padrão para os cookies? Eu coloquei para expirar em 1 hora

**Comment by icaropires** [comment]
Acho que uma abordagem legal seria renovar ele por n (10? 5?) minutos a cada requisição. Só para não deslogar um cara que ta mexendo e sim quem ficar ausente.
