### ISSUE TITLE
Reload causa redirecionamento para a página do Login

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#159]
# Reporte de bugs

## Descrição do problema

Um descrição clara e concisa sobre o problema

## Passos para reprodução

Passos para reproduzir o comportamento.

1. Vá para...
2. Click em...
3. ...

### Comportamento atual

O que está acontecendo atualmente

### Comportamento esperado

Qual é o comportamento esperado pelo sistema

## Contextos, prints e informações adicionais

Se for aplicável, adicione gifs, imagens ou qualquer outro detalhe de
enriqueça a descrição do problema.

## Possível Solução

Caso você tenha algum sugestão de onde começar a procurar o problema ou uma
solução para ele escreva aqui.

**Comment by tmcstiago** [comment]
Esta Issue trata do mesmo bug da #162 e a mesma encontra-se com mais detalhes de informações.
Por este motivo, esta Issue será finalizada
