### ISSUE TITLE
Permitir somente administrador cadastrar usuários

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#163]
## Descrição

Bloquear tela de cadastro para usuários comuns e habilitá-la para o admin.

## Tarefas

- [x] Enviar atributo is_superuser para o frontend e salvar informação no localStorage;
- [x] Utilizar AuthorizedRoute com a prop permission para validar se usuário é admin ou não.

## Informação adicional

O atributo is_superuser pode ser enviado juntamente com o token, o que evitaria realizar outra requisição para acessar essa informação.

**Comment by GabrielTiveron** [comment]
Haverá apenas um usuário admin?

**Comment by tmcstiago** [comment]
Acredito que para uma melhor utilização do Software, o ideal seria ter vário usuários com permissão de admin

**Comment by VictorLeviPeixoto** [comment]
Acredito que não, tendo em vista o poder do mesmo.
Na prática nenhum aluno deveria ter tal acesso, somente alguns professores isso se passar do próprio Evandro
