### ISSUE TITLE
Criar formulário de calibração de força

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#176]
## Descrição

Criar formulário para calibração da força

## Tarefas

- [x] Criar formulário utilizando redux-form-material-ui se baseando na estrutura utilizada no formulário de configuração;
- [ ] Criar botão para submissão das informações para o back-end;
- [x] Integrar gráfico na página.

## Informação adicional

**Comment by tmcstiago** [comment]
Para auxiliar o desenvolvimento do formulário, segue abaixo imagem deste formulário no sistema atual.

![Captura de Tela (7)](https://user-images.githubusercontent.com/26742559/58193543-9bf6e400-7c99-11e9-9b77-4999ecc46d29.png)

**Comment by tmcstiago** [comment]
Conforme informado na #178 , não será incluído o botão de upload nos formulários secundários da calibração.
