### ISSUE TITLE
Criar formulário de calibração de vibração

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#178]
## Descrição

Criar formulário para calibração da vibração

## Tarefas

- [x] Criar formulário utilizando redux-form-material-ui se baseando na estrutura utilizada no formulário de configuração;
- [ ] Criar botão para submissão das informações para o back-end;
- [x] Integrar gráfico na página.

## Informação adicional

**Comment by tmcstiago** [comment]
Para facilitar o trabalho durante o desenvolvimento da Issue, segue imagem desta página no sistema anterior:

![Captura de Tela (9) (1)](https://user-images.githubusercontent.com/26742559/58066769-22f47100-7b61-11e9-958c-2a00fe92e33c.png)

**Comment by tmcstiago** [comment]
O campo Canal de aquisição deve mesmo ter o campo bloqueado?
Entendo que os campos que encontram-se bloqueados são os que recebem informações do sistema, porém o campo "Canal de aquisição" é inserido pelo o usuário através do upload de arquivo.

**Comment by joaorobson** [comment]
Sim, deve ser um campo read-only

**Comment by tmcstiago** [comment]
Em discussão sobre a melhor maneira de utilização do software, foi decidido que não teremos botão para submeter as informações nesta página.
O botão para submeter as informações ficará apenas na aba geral da parte da calibração

**Comment by VictorLeviPeixoto** [comment]
Essa decisão se aplica para todas as issues relacionadas a criação de formulários para a calibração?

**Comment by tmcstiago** [comment]
> Essa decisão se aplica para todas as issues relacionadas a criação de formulários para a calibração?

Sim. O botão para submit será incluído na aba Geral da calibração
