### ISSUE TITLE
Campos com placeholder faltante na calibração 

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#240]
# Reporte de bugs

## Descrição do problema

Alguns campos estão sem placeholder

## Passos para reprodução

1. Ir na página de calibração

### Comportamento atual

Alguns campos estão sem placehilder

### Comportamento esperado

Todos campos deveriam ter placeholder

## Contextos, prints e informações adicionais

Se for aplicável, adicione gifs, imagens ou qualquer outro detalhe de
enriqueça a descrição do problema.

## Possível Solução

Caso você tenha algum sugestão de onde começar a procurar o problema ou uma
solução para ele escreva aqui.

**Comment by tmcstiago** [comment]
Uma issue com o mesmo bug foi aberta na #238
