### ISSUE TITLE
Página configuration não é carregada

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#241]
## Descrição do problema

Página configuration não é carregada

## Passos para reprodução

1. Logar em ambiente de homologação ou produção
2. Clique em 'Configuração no menu'

### Comportamento atual

Página não é carregada

### Comportamento esperado

A página ser carregada

## Contextos, prints e informações adicionais

![image](https://user-images.githubusercontent.com/18473249/59238741-852b1980-8bd5-11e9-8b5b-4af37dd69d82.png)
 
Aparece isso aqui no log

## Possível Solução

Caso você tenha algum sugestão de onde começar a procurar o problema ou uma
solução para ele escreva aqui.

**Comment by tmcstiago** [comment]
Este erro acontece devido a campo "nome" estar nulo.

Para resolução deste problema, sugiro alterar o atributo "key" no component "MenuItem" da função "itensSelection"

**Comment by icaropires** [comment]
Ainda não tem nenhum assignee. Parece um bug prioridade, não?
