### ISSUE TITLE
Recuperar dados de Ensaio do MQTT para o frontend

### ISSUE THREAD

**Issue by GabrielTiveron** [fga-eps-mds/2019.1-unbrake#280]
## Descrição

Utilizar dados vindos do MQTT para serem mostrados na página de ensaio

## Tarefas

- [x] Pegar dados dos canais de Aquisição
- [x] Mostrar na página de Ensaio

**Comment by icaropires** [comment]
Acho que na hora de digitar a pontuação o dedo bateu no 1 sem querer.
