### ISSUE TITLE
Criar Estrutura Analítica do Projeto (EAP)

### ISSUE THREAD

**Issue by ViniciusBernardo** [fga-eps-mds/2019.1-unbrake#29]
## Descrição

Criar diagrama que representa a estrutura analítica do projeto.

## Tarefas

- [x] Associar ao produto UnBrake a definição do produto com suas etapas
- [x] Associar ao produto UnBrake a consolidação do produto com suas etapas

## Informação adicional

**Comment by Bumbleblo** [comment]
Essa issue foi concluída ? Podemos colocar a documentação no gihub-pages ?
