### ISSUE TITLE
Criar autenticação de usuário

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#36]
## Descrição

Criar autenticação de usuário utilizando o Django e provê-la por meio da página de login criada na issue #8.

## Tarefas

- [x] Criar classe para usuário utilizando a configuração básica provida pelo [django admin](https://docs.djangoproject.com/en/2.1/topics/auth/).
- [x] Utilizar o [JWT](https://getblimp.github.io/django-rest-framework-jwt/) para geração de tokens.
- [x] Assegurar que senha está sendo salva encriptada.

**Comment by medeiroslucas** [comment]
Qual parte dessa issue pertence ao front-end? @joaorobson

**Comment by joaorobson** [comment]
As duas útlimas tarefas, @medeiroslucas.

**Comment by VictorLeviPeixoto** [comment]
A issue em si é para criar somente o login, sem signup?

**Comment by RochaCarla** [comment]
critérios de aceita[ção!

**Comment by icaropires** [comment]
> 
> 
> critérios de aceita[ção!


@RochaCarla, essa issue ainda será evoluída quando eu souber melhor o que vou fazer.

Mas estamos mapeando os critérios de aceitação também como tasks. O revisor do PR avaliará se todas as tasks realmente foram cumpridas. Tem problema fazer dessa forma?

**Comment by GabrielTiveron** [comment]
É viável a utilização do pacote django.contrib.auth.models para a criação de um usuário?

**Comment by joaorobson** [comment]
Sim, ele já vem incorporado no Django, certo?

**Comment by GabrielTiveron** [comment]
Sim

**Comment by joaorobson** [comment]
Então está ok usá-lo

**Comment by Bumbleblo** [comment]
@GabrielTiveron conseguiu usar o jwt para gerar os tokens ?

**Comment by GabrielTiveron** [comment]
O graphql tem uma função pra isso, usei ela @Bumbleblo

**Comment by icaropires** [comment]
> O graphql tem uma função pra isso, usei ela @Bumbleblo

@GabrielTiveron , então acho que seria o caso de marcar a task como concluída na descrição da issue.
