### ISSUE TITLE
Criar formulário para calibração de temperatura

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#39]
## Descrição

Criar formulário para calibrar informações relativas aos sensores de temperatura do simulador.

## Tarefas

- [x] Utilizar [redux-form-material-ui](https://github.com/erikras/redux-form-material-ui/tree/5.0) para criar os campos editáveis.
- [x] Integrar o gráfico criado na issue #11 na página criada.
- [x] Utilizar Material-UI para criar o restante dos componentes.
- [x] Relacionar ações dos botões "Plota temperatura 1" e "Plota temperatura 2" com exibição das linhas no gráfico.

## Informação adicional

Abaixo, página correspondente no software utilizado atualmente: 

![calibracao](https://user-images.githubusercontent.com/26315903/55294733-013a0180-53dc-11e9-86cf-7914e9646248.png)

A parte superior onde existem abas de navegação e os botões da parte inferior não necessitam ser implementados na realização dessa issue.

**Comment by Bumbleblo** [comment]
Quem estiver com essa issue por favor se assine conforme está escrito no [guida de contribuição](https://github.com/fga-eps-mds/2019.1-unbrake/blob/devel/CONTRIBUTING.md)

**Comment by Bumbleblo** [comment]
O merge do pull request já foi feito, porque a issue ainda não está na pipe close ? Existe alguma justificativa ?
