### ISSUE TITLE
Linguagem oficial do repositório

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.1-unbrake#4]
Gostaria de abrir uma discussão pública sobre a linguagem oficial que vamos tomar na documentação e código deste projeto.

**Comment by Bumbleblo** [comment]
Acredito que a melhor língua para o projeto seria a língua inglesa. Praticamente quem trabalha com tecnologia (pessoas que poderiam ajudar com o projeto) tem algum nível de conversação em inglês e também um [percentual considerável do planeta consegue se comunicar em inglês](https://pt.wikipedia.org/wiki/Lista_de_l%C3%ADnguas_por_total_de_falantes).

**Comment by icaropires** [comment]
Na mesma linha do @Bumbleblo, sugiro que todas as questões relacionadas a desenvolvimento sejam em inglês, abrindo assim a possibilidade de contribuições e consultas a toda a parte da comunidade do Github conhecedora de inglês, que é bem maior do que a de português.

Já para documentações não diretamentamente relacionadas ao desenvolvimento, acredito que não trará grandes prejuízos serem elaboradas em português (pelo menos incialmente).

**Comment by Bumbleblo** [comment]
Gostaria da opinião da equipe atual do projeto: @icaropires @joaorobson @ViniciusBernardo @VictorLeviPeixoto @GabrielTiveron  [lleticiaarj](https://github.com/leticiaarj) @tmcstiago @medeiroslucas

**Comment by VictorLeviPeixoto** [comment]
Eu concordo com sua opinião @Bumbleblo, também gostaria que a linguagem oficial do projeto seja a inglesa.

**Comment by ViniciusBernardo** [comment]
Eu concordo com a opinião do @icaropires de que apenas questões relacionadas ao desenvolvimento devem ser em inglês.

**Comment by icaropires** [comment]
![image](https://user-images.githubusercontent.com/18473249/54858710-25fbee00-4ce5-11e9-814c-95f3c6c9095b.png)
@joaorobson I guess it's decided.

**Comment by Bumbleblo** [comment]
Yep, I will link that issue in #6 and write that in contributing guidelines.

**Comment by Bumbleblo** [comment]
Linked! I'll close that issue now.

**Comment by Bumbleblo** [comment]
As mentoras[Carla Rochar](https://github.com/RochaCarla) e [Bruna Moreira](https://github.com/brunanayara) chegaram a conclusão que o uso da língua portuguesa seria melhor para o acompanhamento do projeto. Como ambas são mentoras do projeto vamos seguir essa sugestão.
