### ISSUE TITLE
Criar Plano de Custo

### ISSUE THREAD

**Issue by ViniciusBernardo** [fga-eps-mds/2019.1-unbrake#53]
## Descrição

Criar o documento com o plano de custo estimado do projeto

## Tarefas

- [x] Definir valores da mão de obra no tempo estimado do projeto
- [x] Definir valores de lucro e risco do projeto
- [x] Definir valores da infraestrutura e equipamentos do projeto
- [x] Escrever o documento no formato markdown e colocá-lo no github pages do repositório

## Informação adicional

**Comment by Bumbleblo** [comment]
Essa issue foi concluída ? Podemos colocar essa documentação no githu-pages ?
