### ISSUE TITLE
Ignorar diretório de snapshots criado pelo Jest

### ISSUE THREAD

**Issue by joaorobson** [fga-eps-mds/2019.1-unbrake#56]
## Descrição

Adicionar regra no .gitignore para o diretório __snapshots__ no frontend e apagar pasta gerada pela ferramenta.

## Tarefas

- [x] Adicionar regra no arquivo .gitignore.
- [x] Apagar pasta.

**Comment by icaropires** [comment]
@joaorobson 
![image](https://user-images.githubusercontent.com/18473249/56005043-da65b000-5ca4-11e9-9aa1-c1e86e3e7553.png)
Vou reverter as alterações desse patch no #77 . As snapshots devem ser commitadas de acordo com a [documentação do jest](https://jestjs.io/docs/en/snapshot-testing.html#should-snapshot-files-be-committed)
