### ISSUE TITLE
Melhorar o tema da página do projeto

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.1-unbrake#62]
## Descrição

Colocar um tema pre-montado na página do projeto

## Tarefas

- [x] Escolher um tema visualmente aceitável
- [ ] Realizar as configurações necessárias no pelican para que configure o tema corretamente

## Informação adicional

https://docs.getpelican.com/en/stable/pelican-themes.html

**Comment by Bumbleblo** [comment]
Os melhores links que encontrei com temas para o Pelican estão nesse [site](http://pelicanthemes.com/) porém o único que atende as nossas necessidades não está compatível com a versão que estamos utilizando.

**Comment by icaropires** [comment]
Atualizar é uma opção?

**Comment by Bumbleblo** [comment]
Teríamos que entender a fundo como elaborar o tema e provavelmente vamos ter que trabalhar diretamente no html css.

**Comment by Bumbleblo** [comment]
Vou utilizar esse [tema](https://github.com/Parbhat/pelican-blue), ele vai conseguir resolver o problema com os links que estamos tendo agora.

**Comment by Bumbleblo** [comment]
Essa é a versão original com esse tema, a partir dele tem como alterar o template para adicionar algumas outras coisas porém para um versão inicial acredito que está bom.

![2019-04-14-194942_1190x886_scrot](https://user-images.githubusercontent.com/13987085/56100413-c44b3000-5eee-11e9-8314-b81fa8db5234.png)

**Comment by Bumbleblo** [comment]
Já foi realizado o deploy
