### ISSUE TITLE
Configurar ferramentas de folha de estilo e linters para o backend

### ISSUE THREAD

**Issue by icaropires** [fga-eps-mds/2019.1-unbrake#64]
## Descrição

Configurar ferramentas de folha de estilo e linters para o backend para uso local pelos desenvolvedores

## Tarefas

- [x] Escolher ferramenta de folha de estilo
- [x] Integrar ferramenta de folha de estilo
- [x] Se possível, encontrar forma de autocorrigir a folha de estilo
- [x] Escolher ferramenta linter
- [x] Integrar ferramenta linter
- [x] Integrar configurações entre linter e folha de estilo para que não discordem
- [x] Ambas as ferramentas devem ser integradas no esquema de git hooks
- [x] Os chamados dos git hooks devem ser executados em ambiente dockerizado e sem ser necessário intervenção por parte do desenvolvedor
- [x] Atualizar integração contínua para que execute as novas ferramentas integradas

**Comment by icaropires** [comment]
A ferramenta utilizada como checador da folha de estilo será a `flake8`, que também é um linter. Ela é a escolhida por ser amplamente aceita pela comunidade há bastante tempo.

**Comment by icaropires** [comment]
Na minha opinião o flake8 é uma excelente ferramenta para casos de uso mais simples. Mas opto por também utilizar a ferramenta [pylint](https://www.pylint.org/) para checar vários aspectos de linting que a flake8 não detecta: como falta de documentação, falta de atribuição, regex para nomes de variáveis, detecção de erros, entre outros (sim).

Como é um projeto é em django, há também uma extensão que facilita a personalização da configuração do pylint para o django, é a [pylint-django](https://github.com/PyCQA/pylint-django), também integrarei ela.

**Comment by icaropires** [comment]
Eu poderia mas não vou, exceto talvez sob motim, ignorar os avisos do pylint sobre falta de documentação em código. Pois, é uma boa prática e ajudará os outros desenvolvedores e até o próprio implementador mais tarde.

Aos desenvolvedores, @medeiroslucas, @tmcstiago, @leticiadesouza, @VictorLeviPeixoto e @GabrielTiveron, por favor consultar a [pep 257](https://www.python.org/dev/peps/pep-0257/).

**Comment by joaorobson** [comment]
![image](https://www.environmentalpavingsolutions.com/wp-content/uploads/2015/03/ts8QiFV-e1427830513857.jpg)
